<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>Latest</LangVersion>
    <Authors>Koki</Authors>

    <BepInExPluginGuid>com.koki.kokiweapons</BepInExPluginGuid>
    <BepInExPluginName>Koki Weapons</BepInExPluginName>
    <BepInExPluginVersion>2.0.5</BepInExPluginVersion>

    <BepInExPluginDir>C:\Users\koki\AppData\Roaming\com.kesomannen.gale\straftat\profiles\Default\BepInEx\plugins</BepInExPluginDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="*" ExcludeAssets="runtime" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="*" PrivateAssets="all" IncludeAssets="build" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="*" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.45" IncludeAssets="compile" PrivateAssets="all" />
  </ItemGroup>

  <!-- Dependencies -->
  <PropertyGroup>
    <DLLs>D:\SteamLibrary\steamapps\common\STRAFTAT\STRAFTAT_Data\Managed</DLLs>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="kestrel-Mod_Menu" Version="*" />
    <PackageReference Include="straftatmodding-MyceliumNetworking" Version="*" />

    <Reference Include="$(DLLs)\Assembly-CSharp.dll" Publicize="true" />
    <Reference Include="$(DLLs)\ComputerysModdingUtilities.dll" />

    <Reference Include="$(DLLs)\FishNet.Runtime.dll" />
    <Reference Include="$(DLLs)\Unity.InputSystem.dll" />
    <Reference Include="$(DLLs)\com.rlabrecque.steamworks.net.dll" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <IncludeSymbols>true</IncludeSymbols>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <Target Name="CopyDLL" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' ">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BepInExPluginDir)\DEVELOPMENT-BUILD-$(BepInExPluginName)" />
  </Target>
</Project>